spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

---